### ISSUE TITLE
Duplicate aliases generated

### ISSUE THREAD

**Issue by djmarcin** [abrisco/cargo-bazel#157]
From our workspace, we are getting duplicate aliases generated which makes the crate index unusable:
```
alias(
    name = "webpki-roots__process_cert",
    actual = "@crate_index__webpki-roots-0.21.1//:process_cert__bin",
)
alias(
    name = "webpki-roots__process_cert",
    actual = "@crate_index__webpki-roots-0.22.2//:process_cert__bin",
)
```

**Comment by abrisco** [comment]
Odd, do you have different crates depending on these exact versions?

**Comment by abrisco** [comment]
@djmarcin Is there a minimal `Cargo.toml` file you could share that would allow me to reproduce the issue?

**Comment by abrisco** [comment]
Ooooh, coffee's kicking in. These are binary targets. I think I see the issue (though a repro would still be very nice to be able to use in a regression test).
